title: ssb2dmba
email: emmanuel.florent@gmail.com
description: >- 
  ssb-relay.
baseurl: "/ssb-relay/"
url: "https://ssb2dmba.github.io/ssb-relay"
github_username: ssb2dmba

# Build settings
theme: minima
plugins:
  - jekyll-feed
include:
  - dmba.gpg
  - dmba.asc
exclude:
  - src/
  - deb-install/