version: "3"
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - ssb-relay
    restart: always
    environment:
      DOMAINS: 'delog.in -> http://ssb-relay:8000'
      # STAGE: 'production' # Don't use production until staging works
      # FORCE_RENEW: 'true'
    volumes:
      - https-portal-data:/var/lib/https-portal
  ssb-relay:
    restart: on-failure
    build: .
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "8000:8000"
      - "8008:8008"
    command: node dist/index.js
    volumes:
      - ~./ssb:~./ssb
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
volumes:
  https-portal-data: