version: "3"
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - ssb-relay
    restart: always
    environment:
      DOMAINS: 'delog.in -> http://ssb-relay:8000'
      STAGE: 'staging' # Don't use 'production' until staging works
      FORCE_RENEW: 'true'
    volumes:
      - https-portal-data:/var/lib/https-portal
  ssb-relay:
    build:
      context: .
      args:
        USER_ID: $USER
        GROUP_ID: $GROUP
    user: "${USER}:${GROUP}"
    restart: always
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "8000:8000"
      - "8008:8008"
    command: node dist/index.js
    volumes:
      - ~/.ssb:/home/node/.ssb
  postgres:
    user: "${USER}:${GROUP}"
    image: postgres:11
    ports:
      - "5432:5432"
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    - ~/pgdata/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ssb
      POSTGRES_PASSWORD: ssb
      POSTGRES_DB: ssb
volumes:
  https-portal-data:
