name: Release
on:
  push:
    branches:
      - main
      - devel
  repository_dispatch:
    types: [semantic-release]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: ssb
          POSTGRES_USER: ssb
          POSTGRES_DB: ssb

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432    
    steps:
      - name: Checkout[]
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures        
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn semantic-release