name: Deploy Debian repository and SNAPSHOT build

on:
  push:
    branches: ["main", "devrepos"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install required packages
        run: |
          until sudo apt update
          do
            sleep 1
          done
          sudo apt install -y jq

      - name: Insert environment variables
        id: env_config
        run: |
          echo GNUPGHOME="$(mktemp -d /tmp/pgpkeys-XXXXXX)" >> $GITHUB_ENV
          echo REPO_OWNER="$(echo "${GITHUB_REPOSITORY}" | cut -d/ -f1)" >> $GITHUB_ENV
          echo REPO_NAME="$(echo "${GITHUB_REPOSITORY}" | cut -d/ -f2)" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT


      - name: 'Push new tag'
        run: |
           git config user.name "${GITHUB_ACTOR}"
           git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
           VERSION=$(jq -r '.version' package.json)
           SHORTCOMMIT=$(git rev-parse --short HEAD)
           TAG="${VERSION}.${SHORTCOMMIT}"
           git tag $TAG -m "$TAG: nightly build"
           git push origin $TAG
        with:
          token: ${{secrets.PAT}}
